version: '3.1'

services:
  api:
    build:
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongo:27017
    ports:
      - "8080:8080"

  mongo:
    image: mongo:5.0.14
    restart: always
    ports:
      - "27017:27017"