apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-tracker-api
  labels:
    app: movie-tracker
    app.kubernetes.io/name: movie-tracker-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-tracker
  template:
    metadata:
      labels:
        app: movie-tracker
    spec:
      containers:
      - name: movie-tracker
        image: localhost:32000/movie-tracker
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http-web


---
apiVersion: v1
kind: Service
metadata:
  name: movie-tracker-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: movie-tracker-api
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: http-web